import { createAsyncAction } from "typesafe-actions"

const GET_MANUFACTURER_DATA_REQUEST = "GET_MANUFACTURER_DATA_REQUEST"
const GET_MANUFACTURER_DATA_REQUEST_SUCCESS = "GET_MANUFACTURER_DATA_REQUEST_SUCCESS"
const GET_MANUFACTURER_DATA_REQUEST_ERROR = "GET_MANUFACTURER_DATA_REQUEST_ERROR"

export const manufacturer = createAsyncAction(
  GET_MANUFACTURER_DATA_REQUEST,
  GET_MANUFACTURER_DATA_REQUEST_SUCCESS,
  GET_MANUFACTURER_DATA_REQUEST_ERROR,
)<any, Error, undefined>()
